export const Servers = {
  VidStreaming: "vidstreaming",
  MegaCloud: "megacloud",
  StreamSB: "streamsb",
  StreamTape: "streamtape",
  VidCloud: "vidcloud",
  AsianLoad: "asianload",
  GogoCDN: "gogocdn",
  MixDrop: "mixdrop",
  UpCloud: "upcloud",
  VizCloud: "vizcloud",
  MyCloud: "mycloud",
  Filemoon: "filemoon"
};

export const animeCategories = [
  "most-favorite",
  "most-popular",
  "subbed-anime",
  "dubbed-anime",
  "recently-updated",
  "recently-added",
  "top-upcoming",
  "top-airing",
  "movie",
  "special",
  "ova",
  "ona",
  "tv",
  "completed"
];

export const animeGenres = [
  "action",
  "adventure",
  "cars",
  "comedy",
  "dementia",
  "demons",
  "drama",
  "ecchi",
  "fantasy",
  "game",
  "harem",
  "historical",
  "horror",
  "isekai",
  "josei",
  "kids",
  "magic",
  "martial-arts",
  "mecha",
  "military",
  "music",
  "mystery",
  "parody",
  "police",
  "psychological",
  "romance",
  "samurai",
  "school",
  "sci-fi",
  "seinen",
  "shoujo",
  "shoujo-ai",
  "shounen",
  "shounen-ai",
  "slice-of-life",
  "space",
  "sports",
  "super-power",
  "supernatural",
  "thriller",
  "vampire"
];